name: Validacion de Node con Artifacts

on: [push]

jobs:
  verificar-proyecto:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Crear un reporte de prueba
        run: |
          echo "Reporte de ejecucion" > reporte.txt
          echo "Fecha: $(date)" >> reporte.txt
          echo "Estado: Exitoso" >> reporte.txt
        # Aquí estamos creando un archivo real dentro del robot

      - name: Guardar el reporte como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-reporte-bbva       # Nombre del paquete descargable
          path: reporte.txt           # Qué archivo queremos guardar
